### PR TITLE
zoom hover bug in spree 3.2.0

### PR DESCRIPTION
**Pull request by ShuaibMalik1**
bug fixed

### CODE REVIEW

**Comment by vinzloh** [comment]
Hi @ShuaibMalik1 , 
I'm no longer active in this repo, but I'm glad to see people are still using it.
Would you like to be part of the contributor team?

**Comment by Gaurav2728** [comment]
@ShuaibMalik1  @vinzloh I am testing the fix. I'll merge ASAP. Becuase it should work on all `3.2` versions.

**Comment by vinzloh** [comment]
@Gaurav2728 thanks!

**Comment by ShuaibMalik1** [comment]
@Gaurav2728 , @vinzloh 
Yes,  I am happy to be a part of the contributor team.

Thank
Shuaib

**Pull request merged**
