### PR TITLE
update ♨️ ruby version and spree_core, spree_frontend, sass-rails, co…

### PR DESCRIPTION
**Pull request by Gaurav2728**
…ffee-rails version 🚀

* update ruby 2.4.1 and update spree to 3.2+

### CODE REVIEW

**Comment by Gaurav2728** [comment]
@vinzloh hi, I try to update `spree_product_hover_zoom` with latest `spree commerce` framework.
If any change is require please comment and we can also update `spree_product_hover_zoom` version to `1.0.3` for that i have another PR and we can create new tag with that.

**Comment by vinzloh** [comment]
Hi @Gaurav2728! 
Thanks for contributing a PR, hope this gem has been useful for you as it has for me :)

Feel free to make another PR for ```1.0.3```

**Comment by stm9x9** [comment]
hi! @Gaurav2728 perhaps you can have a look at vinzloh/spree_product_zoom, too? would love to see this extension work wit 3.2+, too.

**Comment by Gaurav2728** [comment]
Hi @stm9x9, the currently supported version is `3.2` and you can try it for * 3.2+ *; if you have any issue with that fill free to submit `bug/issue`.

**Comment by stm9x9** [comment]
hi @Gaurav2728 vinzloh/spree_product_zoom seems to be dedicated to spree 3.1.0 :-(

**Comment by Gaurav2728** [comment]
hi @stm9x9, *spree_product_zoom* supports `3.2.x` versions. 
you can use `gem "spree_product_hover_zoom", '~> 1.0.3'` is your project if you want to use spree `3.2.x` version.

**Comment by stm9x9** [comment]
@Gaurav2728 misunderstanding: I don't want to use spree_product_hover_zoom! I must not use a gallery and zoom-on-hover functionality! I want to use https://github.com/vinzloh/spree_product_zoom with lightbox - but I don'T find the correct commits / code changes which would made this plugin work with 3.2.+

**Comment by Gaurav2728** [comment]
@stm9x9 let's chat over the skype - `gauravskype2728` or google hangout - `gaurav2728@gmail.com`

**Comment by vinzloh** [comment]
@Gaurav2728 if you'd like to help @stm9x9 over at  https://github.com/vinzloh/spree_product_zoom let me know, i'll add you as a collaborator there

**Comment by Gaurav2728** [comment]
@vinzloh yup, thank you for your reply but first, let us know the complete requirement and need to send PR.

**Comment by stm9x9** [comment]
@Gaurav2728 thanks for the answer. I would have to reinstall hangout - do you use telegram, too?

**Comment by Gaurav2728** [comment]
@stm9x9 ping me on telegram with `@gaurav2728` 🖐🏻

**Pull request merged**
