### PR TITLE
update spree_product_hover_zoom gem version `1.0.3` 🏁

### PR DESCRIPTION
**Pull request by Gaurav2728**

### CODE REVIEW

**Comment by Gaurav2728** [comment]
@vinzloh 
* you can create 1 tag like `1.0.2` before this commit https://github.com/vinzloh/spree_product_hover_zoom/commit/a61bc57646d735aa470e27ac5a390d83d2260645 that point old ruby and old spree framework support version.

* Release gem to `rubygems.org`

* After merging this (`update gem version 1.0.3`) you can create a new tag that point to latest ruby and spree version.

* Now release update version like `1.0.3` and people can use specific version that they want like `'=>1.0.2'`

* If sounds good you can add me as a `collaborators`

**Comment by vinzloh** [comment]
@Gaurav2728 added as collaborator. go ahead and make it great!

**Comment by vinzloh** [comment]
@Gaurav2728 i think we can start tagging at 1.0.3 onwards for master. 1.0.2 in master now has breaking changes for my project since i merged your previous PR which has a later version of spree. Hence I created another branch 3-1-0 for my project which depends on spree 3-1-0

**Comment by Gaurav2728** [comment]
@vinzloh i would like to thank you for adding me as a `collaborator`.
Yup, I updated ruby and spree version so your build is failing.

* I created a tag `1.0.2` that is pointing https://github.com/vinzloh/spree_product_hover_zoom/commit/c61391c6ad6f88bab281e4bf25a868a246266e12. Gem version `1.0.2` you can found it on `rubygems.org` - https://rubygems.org/gems/spree_product_hover_zoom

* After merging this commit i'll create a new tag `1.0.3` so it's easy to differentiate between old version and new version, i'll also try to create change log for that.

**Comment by vinzloh** [comment]
Thanks @Gaurav2728 !

**Pull request merged**
